describe('Form inputs', () => {
    it('can navigate to the site', () => {
        cy.visit('http://localhost:3000')
        cy.url().should('include', 'localhost')
    })
    it('button is disabled', () => {
        cy.get('button.submit')
        .should('be.disabled')
    })
    it('can type a first name', () => {
        cy.get('input[name="fName"]')
        .type('John')
        .should('have.value', 'John')
    })
    it('can type a last name', () => {
        cy.get('input[name="lName"]')
        .type('Smith')
        .should('have.value', 'Smith')
    })
    it('can type an email', () => {
        cy.get('input[name="email"]')
        .type('John@smith.com')
        .should('have.value', 'John@smith.com')
    })
    it('can type a password', () => {
        cy.get('input[name="password"]')
        .type('password')
        .should('have.value', 'password')
    })
    it('can select TOS', () => {
        cy.get('input[name="accept"]')
        .click()
        .should('have.value', 'on')
    })
    it('button is no longer disabled', () => {
        cy.get('button.submit')
        .should('not.be.disabled')
    })
})

describe('Form validation', () => {
    it('validates first name correctly', () => {
        cy.visit('http://localhost:3000')
        cy.contains('First name must be at least three characters long').should('not.exist')
        cy.get('input[name="fName"]').type('a')
        cy.contains('First name must be at least three characters long').should('exist')
        cy.get('input[name="fName"]').type('b')
        cy.contains('First name must be at least three characters long').should('exist')
        cy.get('input[name="fName"]').type('c')
        cy.contains('First name must be at least three characters long').should('not.exist')
    })
    it('validates last name correctly', () => {
        cy.visit('http://localhost:3000')
        cy.contains('Last name must be at least three characters long').should('not.exist')
        cy.get('input[name="lName"]').type('a')
        cy.contains('Last name must be at least three characters long').should('exist')
        cy.get('input[name="lName"]').type('b')
        cy.contains('Last name must be at least three characters long').should('exist')
        cy.get('input[name="lName"]').type('c')
        cy.contains('Last name must be at least three characters long').should('not.exist')
    })
    it('validates email correctly', () => {
        cy.visit('http://localhost:3000')
        cy.contains('The email must be a valid email address').should('not.exist')
        cy.get('input[name="email"]').type('a')
        cy.contains('The email must be a valid email address').should('exist')
        cy.get('input[name="email"]').type('b')
        cy.contains('The email must be a valid email address').should('exist')
        cy.get('input[name="email"]').type('c')
        cy.contains('The email must be a valid email address').should('exist')
        cy.get('input[name="email"]').type('@')
        cy.contains('The email must be a valid email address').should('exist')
        cy.get('input[name="email"]').type('a')
        cy.contains('The email must be a valid email address').should('exist')
        cy.get('input[name="email"]').type('.')
        cy.contains('The email must be a valid email address').should('exist')
        cy.get('input[name="email"]').type('c')
        cy.contains('The email must be a valid email address').should('not.exist')
    })
    it('validates password correctly', () => {
        cy.visit('http://localhost:3000')
        cy.contains('Password must be at least five characters long').should('not.exist')
        cy.get('input[name="password"]').type('a')
        cy.contains('Password must be at least five characters long').should('exist')
        cy.get('input[name="password"]').type('b')
        cy.contains('Password must be at least five characters long').should('exist')
        cy.get('input[name="password"]').type('c')
        cy.contains('Password must be at least five characters long').should('exist')
        cy.get('input[name="password"]').type('d')
        cy.contains('Password must be at least five characters long').should('exist')
        cy.get('input[name="password"]').type('e')
        cy.contains('Password must be at least five characters long').should('not.exist')
    })
})

describe('Submitting users', () => {
    it('can submit a user', () => {
        cy.visit('http://localhost:3000')
        cy.get('input[name="fName"]').type('John').should('have.value', 'John')
        cy.get('input[name="lName"]').type('Smith').should('have.value', 'Smith')
        cy.get('input[name="email"]').type('John@smith.com').should('have.value', 'John@smith.com')
        cy.get('input[name="password"]').type('abcde').should('have.value', 'abcde')
        cy.get('input[name="accept"]').click()
        cy.get('button.submit').click()
    })
    it('test name', () => {
        cy.get('.user h3').should('have.length', 7)
      })
})